import { Router, Request, Response, NextFunction } from 'express';
import { v4 as uuidv4 } from 'uuid';
import { authenticate } from '../middleware/auth';
import { GeneratedTest } from '../models/GeneratedTest';
import { Project } from '../models/Project';
import { TestRun } from '../models/TestRun';
import { User } from '../models/User';
import { Approval } from '../models/Approval';
import { assertOwned } from '../services/projectAccess';
import { orchestrator } from '../orchestration/WorkflowOrchestrator';
import { PlanLimitError, ValidationError } from '../middleware/errorHandler';
import { recordActivity } from '../services/AiAudit';
import { publishGeneratedWorkspace } from '../ai/git/workspaceGit';
import { generatedFeatureBranch } from '../ai/git/featureBranch';

const router = Router();
router.use(authenticate);

router.get('/', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const where: Record<string, unknown> = { userId: req.user!.userId };
    if (req.query.projectId) where.projectId = req.query.projectId;
    const tests = await GeneratedTest.findAll({
      where,
      order: [['createdAt', 'DESC']],
      include: [
        { association: 'scenario', attributes: ['id', 'scenarioKey', 'title', 'classification'] },
        { association: 'requirement', attributes: ['id', 'key', 'title'] },
        { association: 'project', attributes: ['id', 'name', 'framework'] },
      ],
    });
    res.json({ generatedTests: tests, total: tests.length });
  } catch (err) { next(err); }
});

router.get('/:id', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const test = await GeneratedTest.findByPk(req.params.id, {
      include: [
        { association: 'scenario' },
        { association: 'requirement' },
        { association: 'testPlan' },
      ],
    });
    assertOwned(test, req.user!.userId, 'Generated test');
    res.json(test);
  } catch (err) { next(err); }
});

router.post('/:id/pull-request', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const test = await GeneratedTest.findByPk(req.params.id);
    assertOwned(test, req.user!.userId, 'Generated test');
    const project = await Project.findByPk(test!.projectId);
    if (!project) throw new ValidationError('Project not found');

    const pr = await publishGeneratedWorkspace({
      generated: test!,
      project,
      branchName: generatedFeatureBranch(test!.id),
      title: `testflow: add generated test ${test!.id.slice(0, 8)}`,
      body: 'Generated by TestFlow AI QE after human approval. This does not merge to the default branch.',
    });

    if (!pr.alreadyOpened) {
      await Approval.create({
        projectId: test!.projectId,
        userId: req.user!.userId,
        generatedTestId: test!.id,
        testPlanId: test!.testPlanId,
        decision: 'approved',
        scope: 'git_publish',
      });
    }

    await recordActivity({
      projectId: test!.projectId,
      userId: req.user!.userId,
      action: 'generated_test_pr',
      actor: 'user',
      entityType: 'generated_test',
      entityId: test!.id,
      details: { pullRequestUrl: pr.pullRequestUrl, alreadyOpened: pr.alreadyOpened },
    });
    await test!.reload();
    res.json(test);
  } catch (err) { next(err); }
});

router.post('/:id/execute', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const test = await GeneratedTest.findByPk(req.params.id);
    assertOwned(test, req.user!.userId, 'Generated test');
    const project = await Project.findByPk(test!.projectId);
    if (!project) throw new ValidationError('Project not found');
    if (!test!.files?.length) throw new ValidationError('Generated test has no files to execute');
    const user = await User.findByPk(req.user!.userId);
    if (user && user.monthlyRunsUsed! >= user.monthlyRunsLimit!) {
      throw new PlanLimitError(`Monthly run limit reached (${user.monthlyRunsLimit} runs). Upgrade your plan.`);
    }

    const correlationId = uuidv4();
    const run = await TestRun.create({
      projectId: project.id,
      userId: req.user!.userId,
      status: 'queued',
      branch: project.repoBranch,
      framework: test!.framework,
      triggeredBy: 'dashboard',
      triggerSource: 'ai_generate',
      correlationId,
      testPlanId: test!.testPlanId,
      scenarioId: test!.scenarioId,
      generatedTestId: test!.id,
      queuedAt: new Date(),
    });

    await User.increment('monthlyRunsUsed', { by: 1, where: { id: req.user!.userId } });
    const workflow = await orchestrator.enqueue({
      jobName: 'EXECUTE_GENERATED_TEST',
      projectId: project.id,
      userId: req.user!.userId,
      correlationId,
      generatedTestId: test!.id,
      testRunId: run.id,
      testPlanId: test!.testPlanId,
      entityType: 'generated_test',
      entityId: test!.id,
    });
    await run.update({ workerJobId: workflow.id });
    await test!.update({ executionStatus: 'queued' });
    await recordActivity({
      projectId: test!.projectId,
      userId: req.user!.userId,
      action: 'generated_test_execute',
      actor: 'user',
      entityType: 'generated_test',
      entityId: test!.id,
      details: { runId: run.id },
    });
    res.status(202).json({
      runId: run.id,
      status: 'queued',
      compileStatus: test!.compileStatus,
      executionStatus: 'queued',
    });
  } catch (err) { next(err); }
});

export default router;
