import { Router, Request, Response, NextFunction } from 'express';
import { v4 as uuidv4 } from 'uuid';
import { authenticate } from '../middleware/auth';
import { GeneratedTest } from '../models/GeneratedTest';
import { Project } from '../models/Project';
import { TestRun } from '../models/TestRun';
import { User } from '../models/User';
import { assertOwned } from '../services/projectAccess';
import githubService from '../services/GitHubService';
import { runQueue } from '../services/RunQueue';
import { PlanLimitError, ValidationError } from '../middleware/errorHandler';
import { recordActivity } from '../services/AiAudit';

const router = Router();
router.use(authenticate);

router.get('/', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const where: Record<string, unknown> = { userId: req.user!.userId };
    if (req.query.projectId) where.projectId = req.query.projectId;
    const tests = await GeneratedTest.findAll({
      where,
      order: [['createdAt', 'DESC']],
      include: [
        { association: 'scenario', attributes: ['id', 'scenarioKey', 'title', 'classification'] },
        { association: 'requirement', attributes: ['id', 'key', 'title'] },
        { association: 'project', attributes: ['id', 'name', 'framework'] },
      ],
    });
    res.json({ generatedTests: tests, total: tests.length });
  } catch (err) { next(err); }
});

router.get('/:id', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const test = await GeneratedTest.findByPk(req.params.id, {
      include: [
        { association: 'scenario' },
        { association: 'requirement' },
        { association: 'testPlan' },
      ],
    });
    assertOwned(test, req.user!.userId, 'Generated test');
    res.json(test);
  } catch (err) { next(err); }
});

router.post('/:id/pull-request', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const test = await GeneratedTest.findByPk(req.params.id);
    assertOwned(test, req.user!.userId, 'Generated test');
    const project = await Project.findByPk(test!.projectId);
    if (!project?.repoUrl || !project.repoAccessToken) {
      throw new ValidationError('A GitHub repository and access token are required to open a pull request');
    }
    const pr = await githubService.createPullRequest({
      repoUrl: project.repoUrl,
      token: project.repoAccessToken,
      branchName: `testflow/generated-${test!.id.slice(0, 8)}`,
      baseBranch: project.repoBranch || 'main',
      title: `testflow: add generated test ${test!.id.slice(0, 8)}`,
      body: 'Generated by TestFlow AI QE after human approval. This does not merge to the default branch.',
      files: test!.files || [],
    });
    await test!.update({ status: 'pr_opened', branchName: pr.branchName, pullRequestUrl: pr.pullRequestUrl });
    await recordActivity({
      projectId: test!.projectId,
      userId: req.user!.userId,
      action: 'generated_test_pr',
      actor: 'user',
      entityType: 'generated_test',
      entityId: test!.id,
      details: { pullRequestUrl: pr.pullRequestUrl },
    });
    res.json(test);
  } catch (err) { next(err); }
});

router.post('/:id/execute', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const test = await GeneratedTest.findByPk(req.params.id);
    assertOwned(test, req.user!.userId, 'Generated test');
    const project = await Project.findByPk(test!.projectId);
    if (!project?.repoUrl) throw new ValidationError('Connect a repository before executing generated tests');
    const user = await User.findByPk(req.user!.userId);
    if (user && user.monthlyRunsUsed! >= user.monthlyRunsLimit!) {
      throw new PlanLimitError(`Monthly run limit reached (${user.monthlyRunsLimit} runs). Upgrade your plan.`);
    }

    const correlationId = uuidv4();
    const run = await TestRun.create({
      projectId: project.id,
      userId: req.user!.userId,
      status: 'queued',
      branch: project.repoBranch,
      framework: test!.framework,
      triggeredBy: 'dashboard',
      triggerSource: 'ai_generate',
      correlationId,
      testPlanId: test!.testPlanId,
      scenarioId: test!.scenarioId,
      generatedTestId: test!.id,
      queuedAt: new Date(),
    });

    await User.increment('monthlyRunsUsed', { by: 1, where: { id: req.user!.userId } });
    const job = await runQueue.add('execute-test-run', {
      runId: run.id,
      projectId: project.id,
      userId: req.user!.userId,
      repoUrl: project.repoUrl,
      repoBranch: project.repoBranch,
      repoAccessToken: project.repoAccessToken,
      repoProvider: project.repoProvider,
      framework: project.framework,
      testPattern: project.testPattern,
      environmentVariables: {
        ...(project.environmentVariables || {}),
        APP_URL: project.applicationUrl || '',
      },
      webhookUrl: project.webhookUrl,
      webhookSecret: project.webhookSecret,
    });
    await run.update({ workerJobId: job.id?.toString() });
    await test!.update({ status: 'executed' });
    res.status(202).json({ runId: run.id, status: 'queued' });
  } catch (err) { next(err); }
});

export default router;
